updates to allow spaces in ssds

diff --git a/setup/systemd/cust-net b/setup/systemd/cust-net
--- a/setup/systemd/cust-net
+++ b/setup/systemd/cust-net
@@ -1,9 +1,9 @@
 #!/bin/sh
 # expected to run as root
-# perform WiFi custom setup based on ../hotspot/wifi.json
+# perform WiFi custom setup updating ../hotspot/wifi.json
 # and /etc/NetworkManager/system-connections/
 # 1. If ../hotspot/wifi.json doesn't exist
-# 	start a local WiFi hotspot called Hotspot-`uname -n` with autoconnect-priority=-10
+# 	start a local WiFi hotspot named within $topdir/local_config with autoconnect-priority=-10
 # 	scan for WiFi networks > ../hotspot/wifi.json
 # 	enable a microdot web server to allow network choice
 # 	on choice, connect to the desired network (network file will be created in
@@ -12,21 +12,15 @@
 # 	/etc/NetworkManager/system-connections/, connect to it
 # 3. If the connection cannot be accessed, fall back to the hotspot, rescan and
 # 	start the web server for network choice
-# hotspot_name=Hotspot-1
-# hotspot_password=Hotspot-pass
-# user=pi
 debug=true	# any string
 here=$(dirname $0)
 this=$(basename $0)
-calc_topdir=$(dirname $here)
-topdir=/usr/local/setup
 topdir=$(dirname $here)
 hot_dir=$topdir/hotspot
 application_ssid_file=$topdir/data/application_ssid	# written by network setup job
 kill_file=$topdir/data/kill_file
 log=$topdir/log
 net_file=${hot_dir}/data/wifi.json
-# local_setup uncomments required locales (en_US.UTF8 UTF8) in /etc/locale.gen 
 # import the local_setup generated config
 # contains hotspot_name and hotspot_password
 . $topdir/local_config
@@ -42,10 +36,10 @@ setup_hotspot()
 {
 	# seems that if the ssid is not specified we get Hotspot-`uname -n`
 	logit "nmcli device wifi hotspot ssid $hotspot_name con-name $hotspot_name password $hotspot_password"
-	nmcli device wifi hotspot ssid $hotspot_name con-name $hotspot_name password $hotspot_password || { logit "Can't create wifi hotspot $hotspot_name with password" ;  return 1 ; }
+	nmcli device wifi hotspot ssid "$hotspot_name" con-name "$hotspot_name" password "$hotspot_password" || { logit "Can't create wifi hotspot $hotspot_name with password" ;  return 1 ; }
 	# testing shows that wpa-psk hotspot must have 8 char password or else
 	logit "nmcli connection modify $hotspot_name connection.autoconnect-priority -10 connection.autoconnect yes"
-	nmcli connection modify $hotspot_name connection.autoconnect-priority -10 connection.autoconnect yes || { logit "Can't set priority on hotspot $hotspot_name" ; return 1 ; }
+	nmcli connection modify "$hotspot_name" connection.autoconnect-priority -10 connection.autoconnect yes || { logit "Can't set priority on hotspot $hotspot_name" ; return 1 ; }
 	return 0
 }
 
@@ -61,7 +55,6 @@ start_application()
 
 # MAIN Main main
 logit "starting"
-logit "calc_topdir is $calc_topdir"
 
 # Conditional changes
 # These are mainly for debugging during development and should not be 
@@ -169,7 +162,7 @@ if [ -f $application_ssid_file ] ; then
 	sleep 5
 	logit "Looking for $desired_ssid"
 	logit "nmcli --terse device | grep -w wifi | grep -w connected | grep $desired_ssid"
-	nmcli --terse device | grep -w wifi | grep -w connected | grep $desired_ssid > /dev/null
+	nmcli --terse device | grep -w wifi | grep -w connected | grep "$desired_ssid" > /dev/null
 	if [ $? -eq 0 ] ; then
 		logit "Starting application"
 		start_application
